packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/configs/*'

catalog:
  eslint: ^9.25.1
  stylelint: ^16.20.0
  typescript: ^5.8.3
  prettier: ^3.5.3
  zod: ^3.24.4
  tsup: ^8.5.0

catalogs:
  react-19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.2
    '@types/react-dom': ^19.1.2

  testing:
    vitest: ^3.2.3
    '@vitest/coverage-istanbul': ^3.2.3
    '@vitest/ui': ^3.2.3
    '@testing-library/jest-dom': ^6.6.3
    '@testing-library/react': ^16.3.0
    '@testing-library/user-event': ^14.6.1
    'jsdom': ^26.1.0

  react-router-7:
    react-router: ^7.5.3
    '@react-router/serve': ^7.5.3
    '@react-router/node': '7.5.3'
    '@react-router/dev': ^7.5.3

  node:
    '@types/node': ^22.15.3
